-- Select Schema
use AndreasVacations;

INSERT INTO tbl_countries_iso3166 (id, name_nl)
VALUES
    ('ABW',	N'Aruba'),
    ('AFG',	N'Afghanistan'),
    ('AGO',	N'Angola'),
    ('AIA',	N'Anguilla'),
    ('ALA',	N'Åland'),
    ('ALB',	N'Albanië'),
    ('AND',	N'Andorra'),
    ('ARE',	N'Verenigde Arabische Emiraten'),
    ('ARG',	N'Argentinië'),
    ('ARM',  N'Armenië'),
    ('ASM',	N'Amerikaans-Samoa'),
    ('ATA',	N'Antarctica'),
    ('ATF',	N'Franse Zuidelijke Gebieden'),
    ('ATG',	N'Antigua en Barbuda'),
    ('AUS',	N'Australië'),
    ('AUT',	N'Oostenrijk'),
    ('AZE',	N'Azerbeidzjan'),
    ('BDI',	N'Burundi'),
    ('BEL',	N'België'),
    ('BEN',	N'Benin'),
    ('BES',	N'Bonaire, Sint Eustatius en Saba'),
    ('BFA',	N'Burkina Faso'),
    ('BGD',	N'Bangladesh'),
    ('BGR',	N'Bulgarije'),
    ('BHR',	N'Bahrein'),
    ('BHS',	N'Bahama''s'),
    ('BIH',	N'Bosnië en Herzegovina'),
    ('BLM',	N'Saint Barthélemy'),
    ('BLR',	N'Wit-Rusland'),
    ('BLZ',	N'Belize'),
    ('BMU',	N'Bermuda'),
    ('BOL',	N'Bolivia'),
    ('BRA',	N'Brazilië'),
    ('BRB',	N'Barbados'),
    ('BRN',	N'Brunei Darussalam'),
    ('BTN',	N'Bhutan'),
    ('BVT',	N'Bouvet'),
    ('BWA',	N'Botswana'),
    ('CAF',	N'Centraal-Afrikaanse Republiek'),
    ('CAN',	N'Canada'),
    ('CCK',	N'Cocoseilanden'),
    ('CHE',	N'Zwitserland'),
    ('CHL',	N'Chili'),
    ('CHN',	N'China'),
    ('CIV',	N'Ivoorkust'),
    ('CMR',	N'Kameroen'),
    ('COD',	N'Congo-Kinshasa'),
    ('COG',	N'Congo-Brazzaville'),
    ('COK',	N'Cookeilanden'),
    ('COL',	N'Colombia'),
    ('COM',	N'Comoren'),
    ('CPV',	N'Kaapverdië'),
    ('CRI',	N'Costa Rica'),
    ('CUB',	N'Cuba'),
    ('CUW',	N'Curaçao'),
    ('CXR',	N'Christmaseiland'),
    ('CYM',	N'Kaaimaneilanden'),
    ('CYP',	N'Cyprus'),
    ('CZE',	N'Tsjechië'),
    ('DEU',	N'Duitsland'),
    ('DJI',	N'Djibouti'),
    ('DMA',	N'Dominica'),
    ('DNK',	N'Denemarken'),
    ('DOM',	N'Dominicaanse Republiek'),
    ('DZA',	N'Algerije'),
    ('ECU',	N'Ecuador'),
    ('EGY',	N'Egypte'),
    ('ERI',	N'Eritrea'),
    ('ESH',	N'Westelijke Sahara'),
    ('ESP',	N'Spanje'),
    ('EST',	N'Estland'),
    ('ETH',	N'Ethiopië'),
    ('FIN',	N'Finland'),
    ('FJI',	N'Fiji'),
    ('FLK',	N'Falklandeilanden'),
    ('FRA',	N'Frankrijk'),
    ('FRO',	N'Faeröer'),
    ('FSM',	N'Micronesië'),
    ('GAB',	N'Gabon'),
    ('GBR',	N'Verenigd Koninkrijk'),
    ('GEO',	N'Georgië'),
    ('GGY',	N'Guernsey'),
    ('GHA',	N'Ghana'),
    ('GIB',	N'Gibraltar'),
    ('GIN',	N'Guinee'),
    ('GLP',	N'Guadeloupe'),
    ('GMB',	N'Gambia'),
    ('GNB',	N'Guinee-Bissau'),
    ('GNQ',	N'Equatoriaal Guinea'),
    ('GRC',	N'Griekenland'),
    ('GRD',	N'Grenada'),
    ('GRL',	N'Groenland'),
    ('GTM',	N'Guatemala'),
    ('GUF',	N'Frans-Guyana'),
    ('GUM',	N'Guam'),
    ('GUY',	N'Guyana'),
    ('HKG',	N'Hongkong'),
    ('HMD',	N'Heard en McDonaldeilanden'),
    ('HND',	N'Honduras'),
    ('HRV',	N'Kroatië'),
    ('HTI',	N'Haïti'),
    ('HUN',	N'Hongarije'),
    ('IDN',	N'Indonesië'),
    ('IMN',	N'Man'),
    ('IND',	N'India'),
    ('IOT',	N'Brits Indische Oceaanterritorium'),
    ('IRL',	N'Ierland'),
    ('IRN',	N'Iran'),
    ('IRQ',	N'Irak'),
    ('ISL',	N'IJsland'),
    ('ISR',	N'Israël'),
    ('ITA',	N'Italië'),
    ('JAM',	N'Jamaica'),
    ('JEY',	N'Jersey'),
    ('JOR',	N'Jordanië'),
    ('JPN',	N'Japan'),
    ('KAZ',	N'Kazachstan'),
    ('KEN',	N'Kenia'),
    ('KGZ',	N'Kirgizië'),
    ('KHM',	N'Cambodja'),
    ('KIR',	N'Kiribati'),
    ('KNA',	N'Saint Kitts en Nevis'),
    ('KOR',	N'Zuid-Korea'),
    ('KWT',	N'Koeweit'),
    ('LAO',	N'Laos'),
    ('LBN',	N'Libanon'),
    ('LBR',	N'Liberia'),
    ('LBY',	N'Libië'),
    ('LCA',	N'Saint Lucia'),
    ('LIE',	N'Liechtenstein'),
    ('LKA',	N'Sri Lanka'),
    ('LSO',	N'Lesotho'),
    ('LTU',	N'Litouwen'),
    ('LUX',	N'Luxemburg'),
    ('LVA',	N'Letland'),
    ('MAC',	N'Macau'),
    ('MAF',	N'Sint-Maarten (Frans deel)'),
    ('MAR',	N'Marokko'),
    ('MCO',	N'Monaco'),
    ('MDA',	N'Moldavië'),
    ('MDG',	N'Madagascar'),
    ('MDV',	N'Malediven'),
    ('MEX',	N'Mexico'),
    ('MHL',	N'Marshalleilanden'),
    ('MKD',	N'Noord-Macedonië'),
    ('MLI',	N'Mali'),
    ('MLT',	N'Malta'),
    ('MMR',	N'Myanmar'),
    ('MNE',	N'Montenegro'),
    ('MNG',	N'Mongolië'),
    ('MNP',	N'Noordelijke Marianen'),
    ('MOZ',	N'Mozambique'),
    ('MRT',	N'Mauritanië'),
    ('MSR',	N'Montserrat'),
    ('MTQ',	N'Martinique'),
    ('MUS',	N'Mauritius'),
    ('MWI',	N'Malawi'),
    ('MYS',	N'Maleisië'),
    ('MYT',	N'Mayotte'),
    ('NAM',	N'Namibië'),
    ('NCL',	N'Nieuw-Caledonië'),
    ('NER',	N'Niger'),
    ('NFK',	N'Norfolk'),
    ('NGA',	N'Nigeria'),
    ('NIC',	N'Nicaragua'),
    ('NIU',	N'Niue'),
    ('NLD',	N'Nederland'),
    ('NOR',	N'Noorwegen'),
    ('NPL',	N'Nepal'),
    ('NRU',	N'Nauru'),
    ('NZL',	N'Nieuw-Zeeland'),
    ('OMN',	N'Oman'),
    ('PAK',	N'Pakistan'),
    ('PAN',	N'Panama'),
    ('PCN',	N'Pitcairneilanden'),
    ('PER',	N'Peru'),
    ('PHL',	N'Filipijnen'),
    ('PLW',	N'Palau'),
    ('PNG',	N'Papoea-Nieuw-Guinea'),
    ('POL',	N'Polen'),
    ('PRI',	N'Puerto Rico'),
    ('PRK',	N'Democratische Volksrepubliek Korea'),
    ('PRT',	N'Portugal'),
    ('PRY',	N'Paraguay'),
    ('PSE',	N'Palestina'),
    ('PYF',	N'Frans-Polynesië'),
    ('QAT',	N'Qatar'),
    ('REU',	N'Réunion'),
    ('ROU',	N'Roemenië'),
    ('RUS',	N'Rusland'),
    ('RWA',	N'Rwanda'),
    ('SAU',	N'Saoedi-Arabië'),
    ('SDN',	N'Soedan'),
    ('SEN',	N'Senegal'),
    ('SGP',	N'Singapore'),
    ('SGS',	N'Zuid-Georgia en de Zuidelijke Sandwicheilanden'),
    ('SHN',	N'Sint-Helena'),
    ('SJM',	N'Spitsbergen en Jan Mayen'),
    ('SLB',	N'Salomonseilanden'),
    ('SLE',	N'Sierra Leone'),
    ('SLV',	N'El Salvador'),
    ('SMR',	N'San Marino'),
    ('SOM',	N'Somalië'),
    ('SPM',	N'Saint-Pierre en Miquelon'),
    ('SRB',	N'Servië'),
    ('SSD',	N'Zuid-Soedan'),
    ('STP',	N'Sao Tomé en Principe'),
    ('SUR',	N'Suriname'),
    ('SVK',	N'Slowakije'),
    ('SVN',	N'Slovenië'),
    ('SWE',	N'Zweden'),
    ('SWZ',	N'Swaziland'),
    ('SXM',	N'Sint-Maarten (Nederlands deel)'),
    ('SYC',	N'Seychellen'),
    ('SYR',	N'Syrië'),
    ('TCA',	N'Turks- en Caicoseilanden'),
    ('TCD',	N'Tsjaad'),
    ('TGO',	N'Togo'),
    ('THA',	N'Thailand'),
    ('TJK',	N'Tadjikistan'),
    ('TKL',	N'Tokelau'),
    ('TKM',	N'Turkmenistan'),
    ('TLS',	N'Oost-Timor'),
    ('TON',	N'Tonga'),
    ('TTO',	N'Trinidad en Tobago'),
    ('TUN',	N'Tunesië'),
    ('TUR',	N'Turkije'),
    ('TUV',	N'Tuvalu'),
    ('TZA',	N'Tanzania'),
    ('UGA',	N'Oeganda'),
    ('UKR',	N'Oekraïne'),
    ('UMI',	N'Amerikaanse Kleinere Afgelegen Eilanden'),
    ('URY',	N'Uruguay'),
    ('USA',	N'Verenigde Staten'),
    ('UZB',	N'Oezbekistan'),
    ('VAT',	N'Vaticaanstad'),
    ('VCT',	N'Saint Vincent en de Grenadines'),
    ('VEN',	N'Venezuela'),
    ('VGB',	N'Britse Maagdeneilanden'),
    ('VIR',	N'Amerikaanse Maagdeneilanden'),
    ('VNM',	N'Vietnam'),
    ('VUT',	N'Vanuatu'),
    ('WLF',	N'Wallis en Futuna'),
    ('WSM',	N'Samoa'),
    ('YEM',	N'Jemen'),
    ('ZAF',	N'Zuid-Afrika'),
    ('ZMB',	N'Zambia'),
    ('ZWE',	N'Zimbabwe')
;

--
INSERT INTO tbl_telephone_types (id, name) VALUES
(1, 'mobile'),
(2, 'private'),
(3, 'home');

-- Inserting example data
INSERT INTO tbl_invoice_status_types (id, name) VALUES
(1, 'created'),
(2, 'reminder sent'),
(3, 'paid in full'),
(4, 'waiting for clients');

INSERT INTO tbl_inbound_invoice_status_types (id, name) VALUES
(1, 'received original'),
(2, 'received reminder'),
(3, 'waiting for clients'),
(4, 'paid in full');

INSERT INTO tbl_transportation_types (id, name) VALUES
(1, 'bus'),
(2, 'train'),
(3, 'airplane');

INSERT INTO tbl_poi_type (id, name) VALUES
(1, 'museum'),
(2, 'park'),
(3, 'restaurant'),
(4, 'rock climbing'),
(5, 'exhibition');

INSERT INTO tbl_residence_types (id, name) VALUES
(1, 'Hotel'),
(2, 'Camping Site'),
(3, 'Apartment');

-- Mock Data for tbl_payment_types
INSERT INTO tbl_payment_types (id, name) VALUES
(1, 'Cash'),
(2, 'Credit Card');